current_dir := ${CURDIR}
TARGET := basys3
TOP := switches_leds
SOURCES := ${current_dir}/../switches_leds.sv

# Include your constraint file path(s) below. Use either an XDC file
# or a PCF+SDC pair. Don't use all three file types.
XDC := ${current_dir}/Basys-3-Master.xdc

#include <path to f4pga-examples root directory>/common/common.mk
include ${current_dir}/common.mk